version: '3'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_URL=jdbc:mysql://localhost:3306/app
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass

